In [13]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\hp\anaconda3\lib\site-packages (3.0.9)
Requirement already satisfied: et-xmlfile in c:\users\hp\anaconda3\lib\site-packages (from openpyxl) (1.1.0)

In [14]:
conda install -c anaconda openpyxl

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/win-64/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/r/noarch/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/msys2/noarch/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/msys2/win-64/current_repodata.json HTTP/1.1" 304 0
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/win-64/current_repodata.json HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /anaconda/win-64/current_repodata.json HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /anaconda/noarch/current_repodata.json HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://repo.anaconda.com:443 "GET /pkgs/main/noarch/current_repodata.json HTTP/1.1" 200 None


==> WARNING: A newer version of conda exists. <==
  current version: 23.7.4
  latest version: 25.3.1

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=25.3.1

In [15]:
import pandas as pd
# Reloading the uploaded file to ensure a fresh start
reclamations_data = pd.ExcelFile(r"C:\Users\HP\Downloads\HEALTHCARE\HEALTHCARE\health_care_database\reclamations.xlsx")
reclamations_df = reclamations_data.parse('Sheet1')

# Displaying the first few rows of the dataset to verify the data is loaded correctly
reclamations_df.head()

,Reclamation_ID,Patient_ID,Physician_ID,Admission_ID,ICU_Stay_ID,Complaint_Type,Complaint_Description,Reclamation_Date,Resolution_Duration_Days,Satisfaction_Impact,Status
0,rec1,10006,16174,142345,206504,Error,Inaccurate interpretation of diagnostic test r...,2164-10-28,15,4,Resolved
1,rec2,10011,16175,105331,232110,Delay,Unnecessary delays in preparing the patient fo...,2126-08-22,3,1,Resolved
2,rec3,10013,16176,165520,264446,Error,Incorrect blood type administered during trans...,2125-10-06,9,4,Resolved
3,rec4,10017,16177,199207,204881,Error,Inaccurate interpretation of diagnostic test r...,2149-06-03,21,1,Pending
4,rec5,10019,16178,177759,228977,Error,Incorrect blood type administered during trans...,2163-05-14,17,4,Resolved

In [16]:
# General summary of the dataset
eda_summary_reclamations = {
    "Shape": reclamations_df.shape,
    "Missing Values": reclamations_df.isnull().sum(),
    "Column Data Types": reclamations_df.dtypes,
}

# Analyze the distribution of Complaint Types
complaint_type_counts = reclamations_df['Complaint_Type'].value_counts()

# Analyze the distribution of Reclamation Status
status_counts = reclamations_df['Status'].value_counts()

# Analyze Resolution Duration
resolution_duration_stats = reclamations_df['Resolution_Duration_Days'].describe()

# Analyze Satisfaction Impact
satisfaction_impact_counts = reclamations_df['Satisfaction_Impact'].value_counts()

# Display the EDA summary directly
print("Dataset Shape:", eda_summary_reclamations["Shape"])
print("\nMissing Values:\n", eda_summary_reclamations["Missing Values"])
print("\nColumn Data Types:\n", eda_summary_reclamations["Column Data Types"])

Dataset Shape: (20, 11)

Missing Values:
 Reclamation_ID              0
Patient_ID                  0
Physician_ID                0
Admission_ID                0
ICU_Stay_ID                 0
Complaint_Type              0
Complaint_Description       0
Reclamation_Date            0
Resolution_Duration_Days    0
Satisfaction_Impact         0
Status                      0
dtype: int64

Column Data Types:
 Reclamation_ID              object
Patient_ID                   int64
Physician_ID                 int64
Admission_ID                 int64
ICU_Stay_ID                  int64
Complaint_Type              object
Complaint_Description       object
Reclamation_Date            object
Resolution_Duration_Days     int64
Satisfaction_Impact          int64
Status                      object
dtype: object

In [17]:
#  Encodage des colonnes catégoriques "Complaint_Type" et "Status"

# Vérifier les valeurs uniques avant l'encodage
print("\n Valeurs uniques avant encodage:")
print("Complaint_Type:", reclamations_df["Complaint_Type"].unique())
print("Status:", reclamations_df["Status"].unique())

#  Mapping des valeurs catégoriques en valeurs numériques
complaint_type_mapping = {val: idx for idx, val in enumerate(reclamations_df["Complaint_Type"].unique(), start=1)}
status_mapping = {val: idx for idx, val in enumerate(reclamations_df["Status"].unique(), start=1)}

#  Appliquer l'encodage
reclamations_df["Complaint_Type_Encoded"] = reclamations_df["Complaint_Type"].map(complaint_type_mapping)
reclamations_df["Status_Encoded"] = reclamations_df["Status"].map(status_mapping)

 Valeurs uniques avant encodage:
Complaint_Type: ['Error' 'Delay']
Status: ['Resolved' 'Pending']

In [18]:
reclamations_df.head()

,Reclamation_ID,Patient_ID,Physician_ID,Admission_ID,ICU_Stay_ID,Complaint_Type,Complaint_Description,Reclamation_Date,Resolution_Duration_Days,Satisfaction_Impact,Status,Complaint_Type_Encoded,Status_Encoded
0,rec1,10006,16174,142345,206504,Error,Inaccurate interpretation of diagnostic test r...,2164-10-28,15,4,Resolved,1,1
1,rec2,10011,16175,105331,232110,Delay,Unnecessary delays in preparing the patient fo...,2126-08-22,3,1,Resolved,2,1
2,rec3,10013,16176,165520,264446,Error,Incorrect blood type administered during trans...,2125-10-06,9,4,Resolved,1,1
3,rec4,10017,16177,199207,204881,Error,Inaccurate interpretation of diagnostic test r...,2149-06-03,21,1,Pending,1,2
4,rec5,10019,16178,177759,228977,Error,Incorrect blood type administered during trans...,2163-05-14,17,4,Resolved,1,1

In [19]:
# Liste des colonnes à supprimer (IDs + colonnes texte inutiles pour le modèle)
colonnes_a_supprimer = ["Reclamation_Date","Reclamation_ID", "Patient_ID","Physician_ID","Admission_ID","ICU_Stay_ID","Complaint_Type","Complaint_Description","Status"]

# Suppression
reclamations_df_clean = reclamations_df.drop(columns=colonnes_a_supprimer)

# Vérification du nouveau DataFrame
print("\n✅ Données prêtes pour la modélisation :")
print(reclamations_df_clean.head())

✅ Données prêtes pour la modélisation :
   Resolution_Duration_Days  Satisfaction_Impact  Complaint_Type_Encoded  \
0                        15                    4                       1
1                         3                    1                       2
2                         9                    4                       1
3                        21                    1                       1
4                        17                    4                       1

   Status_Encoded
0               1
1               1
2               1
3               2
4               1

In [20]:
reclamations_df_clean.head()

,Resolution_Duration_Days,Satisfaction_Impact,Complaint_Type_Encoded,Status_Encoded
0,15,4,1,1
1,3,1,2,1
2,9,4,1,1
3,21,1,1,2
4,17,4,1,1

In [21]:
print(reclamations_df_clean.to_string())  # Affiche tout le DataFrame (attention s'il est très grand)

    Resolution_Duration_Days  Satisfaction_Impact  Complaint_Type_Encoded  Status_Encoded
0                         15                    4                       1               1
1                          3                    1                       2               1
2                          9                    4                       1               1
3                         21                    1                       1               2
4                         17                    4                       1               1
5                          2                    5                       1               1
6                          2                    3                       1               1
7                         28                    4                       2               2
8                          1                    5                       1               1
9                         12                    5                       2               1
10                        18                    3                       1               1
11                        26                    1                       1               2
12                        22                    1                       1               2
13                        15                    1                       2               1
14                        25                    3                       2               2
15                        30                    1                       2               2
16                        29                    1                       2               2
17                        20                    3                       2               2
18                        11                    1                       1               1
19                        28                    1                       1               2

In [23]:
reclamations_df_clean.to_csv("reclamations_compl.csv", index=False)

In [24]:
X=reclamations_df_clean.drop('Satisfaction_Impact', axis=1)
Y=reclamations_df_clean['Satisfaction_Impact']

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=5)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(16, 3)
(4, 3)
(16,)
(4,)

In [26]:
#KNN
from sklearn.neighbors import KNeighborsClassifier 
KNN=KNeighborsClassifier(n_neighbors=3) 
KNN.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [27]:
import numpy as np

print(type(X_test))  # Vérifiez le type
if isinstance(X_test, np.ndarray):
    print(X_test.flags)  # Vérifiez les flags du tableau

<class 'pandas.core.frame.DataFrame'>

In [28]:
print(KNN.score(X_test,y_test))                        
print(KNN.score(X_train,y_train))

0.25
0.5625

In [29]:
from sklearn.metrics import classification_report , confusion_matrix

y_pred=KNN.predict(X_test)
print(y_pred)
print(y_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test, y_pred,digits=4))

[1 1 1 1]
2     4
5     5
17    3
19    1
Name: Satisfaction_Impact, dtype: int64
[[1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [1 0 0 0]]
              precision    recall  f1-score   support

           1     0.2500    1.0000    0.4000         1
           3     0.0000    0.0000    0.0000         1
           4     0.0000    0.0000    0.0000         1
           5     0.0000    0.0000    0.0000         1

    accuracy                         0.2500         4
   macro avg     0.0625    0.2500    0.1000         4
weighted avg     0.0625    0.2500    0.1000         4

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\HP\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\HP\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [30]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

# Définir les hyperparamètres à rechercher
param_grid = {
    'n_neighbors': [2,3,5,],
    'p': [1, 2]  # Mesure de la distance : 1 pour la distance de Manhattan, 2 pour la distance euclidienne
}

# Initialiser le modèle KNN
KNN = KNeighborsClassifier()

# Créer l'objet GridSearchCV
grid_search = GridSearchCV(KNN, param_grid, cv=5)  # cv=5 pour une validation croisée à 5 plis

# Exécuter la recherche sur grille
grid_search.fit(X_train, y_train)  

# Accéder aux meilleurs hyperparamètres et à la meilleure performance
best_params = grid_search.best_params_
best_score = grid_search.best_score_

print("Meilleurs hyperparamètres:", best_params)
print("Meilleure performance :", best_score)

Meilleurs hyperparamètres: {'n_neighbors': 3, 'p': 1}
Meilleure performance : 0.4333333333333333

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:725: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(

In [31]:

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report


# Création et entraînement du modèle de régression logistique
logistic_model = LogisticRegression(max_iter=1000, random_state=42)
logistic_model.fit(X_train, y_train)

# Prédiction sur l'ensemble de test
y_pred = logistic_model.predict(X_test)

# Évaluation du modèle
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Classification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.5
Classification Report:
              precision    recall  f1-score   support

           1       0.33      1.00      0.50         1
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           5       1.00      1.00      1.00         1

    accuracy                           0.50         4
   macro avg       0.33      0.50      0.38         4
weighted avg       0.33      0.50      0.38         4

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\HP\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\HP\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [32]:
 # Définition de la grille de recherche des paramètres
param_grid = {'C': [0.001, 0.01, 0.1, 1, 10, 100]}

# Création du modèle de régression logistique
logistic_model = LogisticRegression(max_iter=1000, random_state=42)

# Recherche des meilleurs paramètres avec validation croisée
grid_search = GridSearchCV(logistic_model, param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# Affichage des meilleurs paramètres
print("Meilleurs paramètres trouvés:", grid_search.best_params_)

# Entraînement du modèle avec les meilleurs paramètres
best_logistic_model = grid_search.best_estimator_
best_logistic_model.fit(X_train, y_train)

# Prédiction sur l'ensemble de test
y_pred = best_logistic_model.predict(X_test)

# Évaluation du modèle
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)
print("Classification Report:")
print(classification_report(y_test, y_pred))

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\model_selection\_split.py:725: UserWarning: The least populated class in y has only 2 members, which is less than n_splits=5.
  warnings.warn(

Meilleurs paramètres trouvés: {'C': 0.001}
Accuracy: 0.25
Classification Report:
              precision    recall  f1-score   support

           1       0.25      1.00      0.40         1
           3       0.00      0.00      0.00         1
           4       0.00      0.00      0.00         1
           5       0.00      0.00      0.00         1

    accuracy                           0.25         4
   macro avg       0.06      0.25      0.10         4
weighted avg       0.06      0.25      0.10         4

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\HP\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\HP\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

In [33]:
import pandas as pd

# Charger le fichier Excel
file_path = r"C:\Users\HP\Downloads\HEALTHCARE\HEALTHCARE\health_care_database\PATIENTS.xlsx"
data = pd.read_excel(file_path)

# Afficher les 5 premières lignes
print("Les 5 premières lignes du fichier :")
display(data.head())

Les 5 premières lignes du fichier :

,row_id,subject_id,gender,dob,dod,dod_hosp,dod_ssn,expire_flag,HeightInMeters,WeightInKilograms,...,ChestScan,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos,Email,city
0,9467,10006,F,2094-03-05 00:00:00,2165-08-12 00:00:00,2165-08-12 00:00:00,2165-08-12 00:00:00,1,1.63,84.820000,...,1,0,0,0,1,"No, did not receive any tetanus shot in the pa...",0,1,john.**doe#@apple.**com,Los Angeles
1,9472,10011,F,2090-06-05 00:00:00,2126-08-28 00:00:00,2126-08-28 00:00:00,NaN,1,1.60,71.669998,...,0,0,0,1,1,"Yes, received Tdap",0,0,jane.**smith#@squarespace.**com,San Francisco
2,9474,10013,F,2038-09-03 00:00:00,2125-10-07 00:00:00,2125-10-07 00:00:00,2125-10-07 00:00:00,1,1.78,71.209999,...,0,1,0,0,0,"Yes, received tetanus shot but not sure what type",0,0,michael.**johnson#@zendesk.**com,Boston
3,9478,10017,F,2075-09-21 00:00:00,2152-09-12 00:00:00,NaN,2152-09-12 00:00:00,1,1.78,95.250000,...,0,0,0,1,1,"Yes, received tetanus shot but not sure what type",0,0,emily.**davis#@zoom.**com,Houston
4,9479,10019,M,2114-06-20 00:00:00,2163-05-15 00:00:00,2163-05-15 00:00:00,2163-05-15 00:00:00,1,1.68,78.019997,...,1,0,0,1,0,"No, did not receive any tetanus shot in the pa...",0,0,david.**brown#@alibaba.**com,Houston

In [34]:
# DataFrame length
print(f"Dimensions des données : {data.shape}")

Dimensions des données : (100, 39)

In [35]:

print("\n--- Informations sur les données ---")
print(data.info())
print("\n--- Statistiques descriptives ---")
print(data.describe(include='all'))

--- Informations sur les données ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 39 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   row_id                     100 non-null    int64
 1   subject_id                 100 non-null    int64
 2   gender                     100 non-null    object
 3   dob                        100 non-null    object
 4   dod                        100 non-null    object
 5   dod_hosp                   70 non-null     object
 6   dod_ssn                    77 non-null     object
 7   expire_flag                100 non-null    int64
 8   HeightInMeters             100 non-null    float64
 9   WeightInKilograms          100 non-null    float64
 10  BMI                        100 non-null    float64
 11  HadHeartAttack             100 non-null    int64
 12  HadAngina                  100 non-null    int64
 13  HadStroke                  100 non-null    int64
 14  HadAsthma                  100 non-null    int64
 15  HadSkinCancer              100 non-null    int64
 16  HadCOPD                    100 non-null    int64
 17  HadDepressiveDisorder      100 non-null    int64
 18  HadKidneyDisease           100 non-null    int64
 19  HadArthritis               100 non-null    int64
 20  HadDiabetes                100 non-null    object
 21  DeafOrHardOfHearing        100 non-null    int64
 22  BlindOrVisionDifficulty    100 non-null    int64
 23  DifficultyConcentrating    100 non-null    int64
 24  DifficultyWalking          100 non-null    int64
 25  DifficultyDressingBathing  100 non-null    int64
 26  DifficultyErrands          100 non-null    int64
 27  SmokerStatus               100 non-null    object
 28  ECigaretteUsage            100 non-null    object
 29  ChestScan                  100 non-null    int64
 30  AlcoholDrinkers            100 non-null    int64
 31  HIVTesting                 100 non-null    int64
 32  FluVaxLast12               100 non-null    int64
 33  PneumoVaxEver              100 non-null    int64
 34  TetanusLast10Tdap          100 non-null    object
 35  HighRiskLastYear           100 non-null    int64
 36  CovidPos                   100 non-null    int64
 37  Email                      100 non-null    object
 38  city                       100 non-null    object
dtypes: float64(3), int64(25), object(11)
memory usage: 30.6+ KB
None

--- Statistiques descriptives ---
              row_id    subject_id gender                  dob  \
count     100.000000    100.000000    100                  100
unique           NaN           NaN      2                   99
top              NaN           NaN      F  2058-04-23 00:00:00
freq             NaN           NaN     55                    2
mean    20452.580000  26162.330000    NaN                  NaN
std     10982.043163  16201.834705    NaN                  NaN
min      9467.000000  10006.000000    NaN                  NaN
25%      9526.500000  10068.500000    NaN                  NaN
50%     20209.000000  25128.000000    NaN                  NaN
75%     31391.250000  42276.500000    NaN                  NaN
max     31872.000000  44228.000000    NaN                  NaN

                        dod             dod_hosp              dod_ssn  \
count                   100                   70                   77
unique                  100                   70                   77
top     2165-08-12 00:00:00  2165-08-12 00:00:00  2165-08-12 00:00:00
freq                      1                    1                    1
mean                    NaN                  NaN                  NaN
std                     NaN                  NaN                  NaN
min                     NaN                  NaN                  NaN
25%                     NaN                  NaN                  NaN
50%                     NaN                  NaN                  NaN
75%                     NaN                  NaN                  NaN
max                     NaN                  NaN                  NaN

        expire_flag  HeightInMeters  WeightInKilograms  ...   ChestScan  \
count         100.0      100.000000         100.000000  ...  100.000000
unique          NaN             NaN                NaN  ...         NaN
top             NaN             NaN                NaN  ...         NaN
freq            NaN             NaN                NaN  ...         NaN
mean            1.0        1.703300          85.420000  ...    0.540000
std             0.0        0.113521          22.011935  ...    0.500908
min             1.0        1.470000          49.900002  ...    0.000000
25%             1.0        1.600000          71.669998  ...    0.000000
50%             1.0        1.700000          81.650002  ...    1.000000
75%             1.0        1.800000          97.182499  ...    1.000000
max             1.0        1.980000         204.119995  ...    1.000000

        AlcoholDrinkers  HIVTesting  FluVaxLast12  PneumoVaxEver  \
count        100.000000  100.000000     100.00000     100.000000
unique              NaN         NaN           NaN            NaN
top                 NaN         NaN           NaN            NaN
freq                NaN         NaN           NaN            NaN
mean           0.400000    0.250000       0.57000       0.520000
std            0.492366    0.435194       0.49757       0.502117
min            0.000000    0.000000       0.00000       0.000000
25%            0.000000    0.000000       0.00000       0.000000
50%            0.000000    0.000000       1.00000       1.000000
75%            1.000000    0.250000       1.00000       1.000000
max            1.000000    1.000000       1.00000       1.000000

                                        TetanusLast10Tdap  HighRiskLastYear  \
count                                                 100        100.000000
unique                                                  4               NaN
top     No, did not receive any tetanus shot in the pa...               NaN
freq                                                   40               NaN
mean                                                  NaN          0.020000
std                                                   NaN          0.140705
min                                                   NaN          0.000000
25%                                                   NaN          0.000000
50%                                                   NaN          0.000000
75%                                                   NaN          0.000000
max                                                   NaN          1.000000

          CovidPos                    Email         city
count   100.000000                      100          100
unique         NaN                      100           10
top            NaN  john.**doe#@apple.**com  Los Angeles
freq           NaN                        1           13
mean      0.350000                      NaN          NaN
std       0.479372                      NaN          NaN
min       0.000000                      NaN          NaN
25%       0.000000                      NaN          NaN
50%       0.000000                      NaN          NaN
75%       1.000000                      NaN          NaN
max       1.000000                      NaN          NaN

[11 rows x 39 columns]

In [36]:
# Gestion des valeurs manquantes
missing_values = data.isnull().sum()
print("\n--- Valeurs manquantes par colonne ---")
print(missing_values)

--- Valeurs manquantes par colonne ---
row_id                        0
subject_id                    0
gender                        0
dob                           0
dod                           0
dod_hosp                     30
dod_ssn                      23
expire_flag                   0
HeightInMeters                0
WeightInKilograms             0
BMI                           0
HadHeartAttack                0
HadAngina                     0
HadStroke                     0
HadAsthma                     0
HadSkinCancer                 0
HadCOPD                       0
HadDepressiveDisorder         0
HadKidneyDisease              0
HadArthritis                  0
HadDiabetes                   0
DeafOrHardOfHearing           0
BlindOrVisionDifficulty       0
DifficultyConcentrating       0
DifficultyWalking             0
DifficultyDressingBathing     0
DifficultyErrands             0
SmokerStatus                  0
ECigaretteUsage               0
ChestScan                     0
AlcoholDrinkers               0
HIVTesting                    0
FluVaxLast12                  0
PneumoVaxEver                 0
TetanusLast10Tdap             0
HighRiskLastYear              0
CovidPos                      0
Email                         0
city                          0
dtype: int64

In [43]:
# Encode the 'gender' column: F -> 0, M -> 1
if 'gender' in data.columns:
    data['gender_encoded'] = data['gender'].map({'F': 0, 'M': 1})

In [44]:
# Encode the 'HadDiabetes' column: Yes -> 1, No -> 0
if 'HadDiabetes' in data.columns:
    data['HadDiabetes_encoded'] = data['HadDiabetes'].map({'Yes': 1, 'No': 0})

In [45]:
print(data.columns)

Index(['gender', 'dob', 'dod', 'dod_hosp', 'dod_ssn', 'expire_flag',
       'HadHeartAttack', 'HadAngina', 'HadStroke', 'HadAsthma',
       'HadSkinCancer', 'HadCOPD', 'HadDepressiveDisorder', 'HadKidneyDisease',
       'HadArthritis', 'HadDiabetes', 'DeafOrHardOfHearing',
       'BlindOrVisionDifficulty', 'DifficultyConcentrating',
       'DifficultyWalking', 'DifficultyDressingBathing', 'DifficultyErrands',
       'SmokerStatus', 'ECigaretteUsage', 'ChestScan', 'AlcoholDrinkers',
       'HIVTesting', 'FluVaxLast12', 'PneumoVaxEver', 'TetanusLast10Tdap',
       'HighRiskLastYear', 'CovidPos', 'gender_encoded',
       'HadDiabetes_encoded'],
      dtype='object')

In [58]:
# Liste des colonnes à supprimer (IDs + colonnes texte inutiles pour le modèle)
colonnes_supprimer = ['gender', 'dob', 'dod', 'dod_hosp', 'dod_ssn','TetanusLast10Tdap','ECigaretteUsage','SmokerStatus','HadDiabetes_encoded',"HadDiabetes" ]

# Suppression
df_clean = data.drop(columns=colonnes_supprimer)

# Vérification du nouveau DataFrame
print("\n✅ Données prêtes pour la modélisation :")
print(df_clean.head())

✅ Données prêtes pour la modélisation :
   expire_flag  HadHeartAttack  HadAngina  HadStroke  HadAsthma  \
0            1               0          1          0          1
1            1               0          0          0          0
2            1               0          0          0          0
3            1               0          0          0          0
4            1               0          0          0          0

   HadSkinCancer  HadCOPD  HadDepressiveDisorder  HadKidneyDisease  \
0              1        0                      0                 0
1              0        0                      0                 0
2              0        0                      0                 0
3              0        0                      0                 0
4              0        0                      0                 0

   HadArthritis  ...  DifficultyDressingBathing  DifficultyErrands  ChestScan  \
0             1  ...                          0                  0          1
1             1  ...                          0                  0          0
2             0  ...                          0                  0          0
3             1  ...                          0                  0          0
4             0  ...                          0                  0          1

   AlcoholDrinkers  HIVTesting  FluVaxLast12  PneumoVaxEver  HighRiskLastYear  \
0                0           0             0              1                 0
1                0           0             1              1                 0
2                1           0             0              0                 0
3                0           0             1              1                 0
4                0           0             1              0                 0

   CovidPos  gender_encoded
0         1               0
1         0               0
2         0               0
3         0               0
4         0               1

[5 rows x 24 columns]

In [59]:
print(df_clean.columns)

Index(['expire_flag', 'HadHeartAttack', 'HadAngina', 'HadStroke', 'HadAsthma',
       'HadSkinCancer', 'HadCOPD', 'HadDepressiveDisorder', 'HadKidneyDisease',
       'HadArthritis', 'DeafOrHardOfHearing', 'BlindOrVisionDifficulty',
       'DifficultyConcentrating', 'DifficultyWalking',
       'DifficultyDressingBathing', 'DifficultyErrands', 'ChestScan',
       'AlcoholDrinkers', 'HIVTesting', 'FluVaxLast12', 'PneumoVaxEver',
       'HighRiskLastYear', 'CovidPos', 'gender_encoded'],
      dtype='object')

In [61]:

print("\n--- Informations sur les données ---")
print(df_clean.info())

--- Informations sur les données ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   expire_flag                100 non-null    int64
 1   HadHeartAttack             100 non-null    int64
 2   HadAngina                  100 non-null    int64
 3   HadStroke                  100 non-null    int64
 4   HadAsthma                  100 non-null    int64
 5   HadSkinCancer              100 non-null    int64
 6   HadCOPD                    100 non-null    int64
 7   HadDepressiveDisorder      100 non-null    int64
 8   HadKidneyDisease           100 non-null    int64
 9   HadArthritis               100 non-null    int64
 10  DeafOrHardOfHearing        100 non-null    int64
 11  BlindOrVisionDifficulty    100 non-null    int64
 12  DifficultyConcentrating    100 non-null    int64
 13  DifficultyWalking          100 non-null    int64
 14  DifficultyDressingBathing  100 non-null    int64
 15  DifficultyErrands          100 non-null    int64
 16  ChestScan                  100 non-null    int64
 17  AlcoholDrinkers            100 non-null    int64
 18  HIVTesting                 100 non-null    int64
 19  FluVaxLast12               100 non-null    int64
 20  PneumoVaxEver              100 non-null    int64
 21  HighRiskLastYear           100 non-null    int64
 22  CovidPos                   100 non-null    int64
 23  gender_encoded             100 non-null    int64
dtypes: int64(24)
memory usage: 18.9 KB
None

In [115]:
X=df_clean.drop('CovidPos', axis=1)
Y=df_clean['CovidPos']

In [116]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=5)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(80, 23)
(20, 23)
(80,)
(20,)

In [117]:
#KNN
from sklearn.neighbors import KNeighborsClassifier 
KNN=KNeighborsClassifier(n_neighbors=3) 
KNN.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [132]:
# Création du modèle KNN
knn = KNeighborsClassifier(n_neighbors=3)  # Vous pouvez ajuster le nombre de voisins

# Entraînement du modèle
knn.fit(X_train, y_train)

# Prédiction sur l'ensemble de test
y_pred = knn.predict(X_test)

# Afficher la précision sur les ensembles de test et d'entraînement
print("Précision sur l'ensemble de test : ", knn.score(X_test, y_test))
print("Précision sur l'ensemble d'entraînement : ", knn.score(X_train, y_train))

# Évaluation du modèle
print(classification_report(y_test, y_pred))

Précision sur l'ensemble de test :  0.65
Précision sur l'ensemble d'entraînement :  0.75
              precision    recall  f1-score   support

           0       0.85      0.69      0.76        16
           1       0.29      0.50      0.36         4

    accuracy                           0.65        20
   macro avg       0.57      0.59      0.56        20
weighted avg       0.73      0.65      0.68        20

In [134]:
import numpy as np

print(np.isnan(X_train).sum())  # Compter les NaN dans X_train
print(np.isnan(X_test).sum())   # Compter les NaN dans X_test

0
0

In [135]:
print("Précision sur l'ensemble de test : ", knn.score(X_test, y_test))
print("Précision sur l'ensemble d'entraînement : ", knn.score(X_train, y_train))

Précision sur l'ensemble de test :  0.65
Précision sur l'ensemble d'entraînement :  0.75

In [136]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

# Définir les hyperparamètres à rechercher
param_grid = {
    'n_neighbors': [3, 5, 7],
    'p': [1, 2]  # Mesure de la distance : 1 pour la distance de Manhattan, 2 pour la distance euclidienne
}

# Initialiser le modèle KNN
KNN = KNeighborsClassifier()

# Créer l'objet GridSearchCV
grid_search = GridSearchCV(KNN, param_grid, cv=5)  # cv=5 pour une validation croisée à 5 plis

# Exécuter la recherche sur grille
grid_search.fit(X_train, y_train)  

# Accéder aux meilleurs hyperparamètres et à la meilleure performance
best_params = grid_search.best_params_
best_score = grid_search.best_score_

print("Meilleurs hyperparamètres:", best_params)
print("Meilleure performance :", best_score)

Meilleurs hyperparamètres: {'n_neighbors': 5, 'p': 1}
Meilleure performance : 0.65

In [137]:
from sklearn.tree import DecisionTreeClassifier

In [138]:
dt=DecisionTreeClassifier(random_state=0)
model=dt.fit(X_train, y_train)

In [139]:
y_pred = dt.predict(X_test)

In [140]:
from sklearn.metrics import accuracy_score,classification_report
accuracy = accuracy_score(y_test, y_pred)
accuracy
print(classification_report(y_test,y_pred,digits=4))

              precision    recall  f1-score   support

           0     0.8182    0.5625    0.6667        16
           1     0.2222    0.5000    0.3077         4

    accuracy                         0.5500        20
   macro avg     0.5202    0.5312    0.4872        20
weighted avg     0.6990    0.5500    0.5949        20

In [141]:
from sklearn.model_selection import GridSearchCV
param_grid={'criterion':['gini','entropy'],'max_depth':list(range(1,5))}
grid=GridSearchCV(DecisionTreeClassifier(),param_grid,cv=3) #cv-> bch yaamel crossvalidation 5fois
grid.fit(X_train,y_train)

GridSearchCV(cv=3, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [1, 2, 3, 4]})

In [142]:
print(grid.best_score_)
print(grid.best_params_)

0.6614434947768281
{'criterion': 'gini', 'max_depth': 3}

In [143]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split


best_params = {'criterion': 'entropy', 'max_depth': 4}

# Créer le classificateur de base avec les meilleurs paramètres
base_classifier = DecisionTreeClassifier(criterion=best_params['criterion'], max_depth=best_params['max_depth'])

# Créer le modèle de bagging avec le classificateur de base et d'autres paramètres
bagging_model = BaggingClassifier(base_estimator=base_classifier, n_estimators=10, random_state=42, oob_score=True)

# Entraîner le modèle de bagging sur les données d'entraînement
bagging_model.fit(X_train, y_train)

# Calculer et afficher le score du modèle sur les données de test
score = bagging_model.score(X_test, y_test)
print("Score du modèle de bagging:", score)

# Afficher la valeur de l'évaluation OOB
oob_score = bagging_model.oob_score_
print("Score OOB du modèle de bagging avec Random Forest:", oob_score)

Score du modèle de bagging: 0.65
Score OOB du modèle de bagging avec Random Forest: 0.725

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\ensemble\_base.py:156: FutureWarning: `base_estimator` was renamed to `estimator` in version 1.2 and will be removed in 1.4.
  warnings.warn(